{% set name = "researchpy" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/researchpy-{{ version }}.tar.gz
  sha256: 53ff4294675aa2a80abc5922ef165e2a5da3d0305a27e58035fb15396d281733

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0
    - pip
  run:
    - python >=3.7
    - scipy
    - numpy
    - pandas
    - statsmodels
    - patsy

test:
  imports:
    - researchpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/researchpy/researchpy
  summary: Researchpy produces Pandas DataFrames that contain relevant statistical testing information that is commonly required for academic research.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
